EResourceType =
{
    --common
    ["ERT_POPUP_BUTTON_BLUE0"]                  = "ERT_POPUP_BUTTON_BLUE0";
    ["ERT_POPUP_BUTTON_BLUE1"]                  = "ERT_POPUP_BUTTON_BLUE1";
    ["ERT_POPUP_BUTTON_GREEN"]                  = "ERT_POPUP_BUTTON_GREEN";
    
    ["ERT_BUTTON_SHOP"]                         = "ERT_BUTTON_SHOP";
    ["ERT_BUTTON_HELP"]                         = "ERT_BUTTON_HELP";
    
    ["ERT_VIEW_CURRENCY"]                       = "ERT_VIEW_CURRENCY";
    
    ["ERT_ICON_CURRENCY"]                       = "ERT_ICON_CURRENCY";
    ["ERT_ICON_ENERGY"]                         = "ERT_ICON_ENERGY";
    
    
    --state map
    
    ["ERT_STATE_MAP_VIEW_TIME_BONUS"]           = "ERT_STATE_MAP_VIEW_TIME_BONUS";
    ["ERT_STATE_MAP_VIEW_TIME_ENERGY"]          = "ERT_STATE_MAP_VIEW_TIME_ENERGY";
    
    
    ["ERT_STATE_MAP_MAP_PART"]                  = "ERT_STATE_MAP_MAP_PART";
    ["ERT_STATE_MAP_VIEW_GRASS"]                = "ERT_STATE_MAP_VIEW_GRASS";
    
    ["ERT_STATE_MAP_BUTTON_SOUND"]              = "ERT_STATE_MAP_BUTTON_SOUND";
    ["ERT_STATE_MAP_BUTTON_SOUND_DISABLED"]     = "ERT_STATE_MAP_BUTTON_SOUND_DISABLED";
    ["ERT_STATE_MAP_BUTTON_BONUS"]              = "ERT_STATE_MAP_BUTTON_BONUS";
    ["ERT_STATE_MAP_VIEW_BONUS_TIMER"]          = "ERT_STATE_MAP_VIEW_BONUS_TIMER";
    
    ["ERT_STATE_MAP_BUTTON_FREE_CURRENCY"]      = "ERT_STATE_MAP_BUTTON_FREE_CURRENCY";
    
    ["ERT_STATE_MAP_VIEW_ENERGY"]               = "ERT_STATE_MAP_VIEW_ENERGY";
    ["ERT_STATE_MAP_VIEW_ENERGY_TIMER"]         = "ERT_STATE_MAP_VIEW_ENERGY_TIMER";
    
    ["ERT_STATE_MAP_ITEM_COMPLETE"]             = "ERT_STATE_MAP_ITEM_COMPLETE";
    ["ERT_STATE_MAP_ITEM_COMPLETE_ICON"]        = "ERT_STATE_MAP_ITEM_COMPLETE_ICON";
    
    ["ERT_STATE_MAP_ITEM_CURRENT"]              = "ERT_STATE_MAP_ITEM_CURRENT";
    ["ERT_STATE_MAP_ITEM_CURRENT_ANIMATION"]    = "ERT_STATE_MAP_ITEM_CURRENT_ANIMATION";
    
    ["ERT_STATE_MAP_ITEM_CLOSE"]                = "ERT_STATE_MAP_ITEM_CLOSE";
    
    --state game
    ["ERT_STATE_GAME_BACKGROUND"]               = "ERT_STATE_GAME_BACKGROUND";
    
    ["ERT_STATE_GAME_BUTTON_HOME"]              = "ERT_STATE_GAME_BUTTON_HOME";
    
    ["ERT_STATE_GAME_VIEW_TIME"]                = "ERT_STATE_GAME_VIEW_TIME";
    
    ["ERT_STATE_GAME_BUTTON_RESOLVE"]           = "ERT_STATE_GAME_BUTTON_RESOLVE";
    ["ERT_STATE_GAME_BUTTON_SHOW_TURN"]         = "ERT_STATE_GAME_BUTTON_SHOW_TURN";
    ["ERT_STATE_GAME_BUTTON_ADD_TIME"]          = "ERT_STATE_GAME_BUTTON_ADD_TIME";
    
    --cells
    ["ERT_STATE_GAME_CELL_START"]               = "ERT_STATE_GAME_CELL_START";
    ["ERT_STATE_GAME_CELL_END"]                 = "ERT_STATE_GAME_CELL_END";
    ["ERT_STATE_GAME_CELL_END_FULL"]            = "ERT_STATE_GAME_CELL_END_FULL";
    ["ERT_STATE_GAME_CELL_PATH"]                = "ERT_STATE_GAME_CELL_PATH";
    ["ERT_STATE_GAME_CELL_DEFAULT"]             = "ERT_STATE_GAME_CELL_DEFAULT";
    ["ERT_STATE_GAME_CELL_BARRIER"]             = "ERT_STATE_GAME_CELL_BARRIER";
    ["ERT_STATE_GAME_CELL_BRIDGE"]              = "ERT_STATE_GAME_CELL_BRIDGE";
    ["ERT_STATE_GAME_ANIMATION_DOG_DOWN"]       = "ERT_STATE_GAME_ANIMATION_DOG_DOWN";
    ["ERT_STATE_GAME_ANIMATION_DOG_IDLE"]       = "ERT_STATE_GAME_ANIMATION_DOG_IDLE";
    ["ERT_STATE_GAME_ANIMATION_DOG_UP"]         = "ERT_STATE_GAME_ANIMATION_DOG_UP";
    
    --popup bonus
    ["ERT_POPUP_BONUS_VIEW_TIME"]               = "ERT_POPUP_BONUS_VIEW_TIME";
    ["ERT_POPUP_BONUS_VIEW_REWARD"]             = "ERT_POPUP_BONUS_VIEW_REWARD";
    ["ERT_POPUP_BONUS_ARROW"]                   = "ERT_POPUP_BONUS_ARROW";
    ["ERT_POPUP_BONUS_DRUM"]                    = "ERT_POPUP_BONUS_DRUM";
    ["ERT_POPUP_BONUS_VIEW_DRUM"]               = "ERT_POPUP_BONUS_VIEW_DRUM";
    
    
    --popup no resource
    ["ERT_POPUP_NO_RESOURCE_VIEW_TEXT"]           = "ERT_POPUP_NO_RESOURCE_VIEW_TEXT";
    
    --popup game over
    ["ERT_POPUP_GAME_OVER_VIEW_ANIMATION_DOG"]  = "ERT_POPUP_GAME_OVER_VIEW_ANIMATION_DOG";
    ["ERT_POPUP_GAME_OVER_VIEW_PENALTY"]        = "ERT_POPUP_GAME_OVER_VIEW_PENALTY";
    ["ERT_POPUP_GAME_OVER_VIEW_TEXT"]           = "ERT_POPUP_GAME_OVER_VIEW_TEXT";
    
    
    --popup win
    ["ERT_POPUP_WIN_VIEW_TEXT"]                 = "ERT_POPUP_WIN_VIEW_TEXT";
    ["ERT_POPUP_WIN_VIEW_REWARD"]               = "ERT_POPUP_WIN_VIEW_REWARD";
    ["ERT_POPUP_WIN_ANIMATION_DOG"]             = "ERT_POPUP_WIN_ANIMATION_DOG";
    ["ERT_POPUP_WIN_ANIMATION_BALLOONS"]        = "ERT_POPUP_WIN_ANIMATION_BALLOONS";
    
    
    --popup shop
    ["ERT_POPUP_SHOP_VIEW_ITEM"]                = "ERT_POPUP_SHOP_VIEW_ITEM";
    
    --state editor
    
    ["ERT_STATE_EDITOR_BUTTON_SHUFFLE"]    = "ERT_STATE_EDITOR_BUTTON_SHUFFLE";
    ["ERT_STATE_EDITOR_BUTTON_ADD"]        = "ERT_STATE_EDITOR_BUTTON_ADD";
    ["ERT_STATE_EDITOR_BUTTON_REMOVE"]     = "ERT_STATE_EDITOR_BUTTON_REMOVE";
    
}

