EStringType = 
{
    
    --tutorial
    ["EST_POPUP_TUTORIAL_BUTTON_CLOSE"]     = "EST_POPUP_TUTORIAL_BUTTON_CLOSE";
    ["EST_POPUP_TUTORIAL_BUTTON_NEXT"]      = "EST_POPUP_TUTORIAL_BUTTON_NEXT";
    
    ["EST_POPUP_TUTORIAL_TITLE_1"]          = "EST_POPUP_TUTORIAL_TITLE_1";
    ["EST_POPUP_TUTORIAL_TITLE_2"]          = "EST_POPUP_TUTORIAL_TITLE_2";
    ["EST_POPUP_TUTORIAL_TEXT_2"]           = "EST_POPUP_TUTORIAL_TEXT_2";
    
    ["EST_POPUP_TUTORIAL_TITLE_3"]          = "EST_POPUP_TUTORIAL_TITLE_3";
    ["EST_POPUP_TUTORIAL_TEXT_3"]           = "EST_POPUP_TUTORIAL_TEXT_3";
    
    --no currency
    ["EST_POPUP_NO_CURRENCY_TITLE"]         = "EST_POPUP_NO_CURRENCY_TITLE";
    ["EST_POPUP_NO_CURRENCY_TEXT"]          = "EST_POPUP_NO_CURRENCY_TEXT";
    
    
    --no energy
    ["EST_POPUP_NO_ENERGY_TITLE"]           = "EST_POPUP_NO_ENERGY_TITLE";
    ["EST_POPUP_NO_ENERGY_TEXT"]            = "EST_POPUP_NO_ENERGY_TEXT";
    
    
    --no resource
    ["EST_POPUP_NO_RESOURCE_BUTTON_CLOSE"]  = "EST_POPUP_NO_RESOURCE_BUTTON_CLOSE";
    ["EST_POPUP_NO_RESOURCE_BUTTON_BUY"]    = "EST_POPUP_NO_ENERGY_BUTTON_BUY";
    
    --bonus
    ["EST_POPUP_BONUS_TITLE"]               = "EST_POPUP_BONUS_TITLE";
    ["EST_POPUP_BONUS_TIME"]                = "EST_POPUP_BONUS_TIME";
    ["EST_POPUP_BONUS_BUTTON_CLOSE"]        = "EST_POPUP_BONUS_BUTTON_CLOSE";
    ["EST_POPUP_BONUS_REWARD"]              = "EST_POPUP_BONUS_REWARD";
    ["EST_POPUP_BONUS_BUTTON_SPIN"]         = "EST_POPUP_BONUS_BUTTON_SPIN";
    ["EST_POPUP_BONUS_BUTTON_BUY"]          = "EST_POPUP_BONUS_BUTTON_BUY";
    
    --game over
    ["EST_POPUP_GAME_OVER_TITLE"]           = "EST_POPUP_GAME_OVER_TITLE";
    ["EST_POPUP_GAME_OVER_BUTTON_CLOSE"]    = "EST_POPUP_GAME_OVER_BUTTON_CLOSE";
    ["EST_POPUP_GAME_OVER_TEXT"]            = "EST_POPUP_GAME_OVER_TEXT";
    
    
    --win
    ["EST_POPUP_WIN_TITLE"]                 = "EST_POPUP_WIN_TITLE";
    ["EST_POPUP_WIN_TEXT"]                  = "EST_POPUP_WIN_TEXT";
    ["EST_POPUP_WIN_REWARD"]                = "EST_POPUP_WIN_REWARD";
    ["EST_POPUP_WIN_BUTTON_CLOSE"]          = "EST_POPUP_WIN_BUTTON_CLOSE";
    
    
    -- shop
    ["EST_POPUP_SHOP_TITLE"]                = "EST_POPUP_SHOP_TITLE";
    ["EST_POPUP_SHOP_BUTTON_ENERGY"]        = "EST_POPUP_SHOP_BUTTON_ENERGY";
    ["EST_POPUP_SHOP_BUTTON_CURRENCY"]      = "EST_POPUP_SHOP_BUTTON_CURRENCY";
    ["EST_POPUP_SHOP_BUTTON_CLOSE"]         = "EST_POPUP_SHOP_BUTTON_CLOSE";
    
    ["EST_POPUP_SHOP_BUTTON_BUY"]           = "EST_POPUP_SHOP_BUTTON_BUY";
    
    --map
    ["EST_STATE_MAP_FREE_CURRENCY"]         = "EST_STATE_MAP_FREE_CURRENCY";
    
    --game
    ["EST_GAME_SCORES"]                     = "EST_GAME_SCORES";
    
    ["EST_GAME_PURCHASE_FREE"]              = "EST_GAME_PURCHASE_FREE";
    
}

