EBonusType =
{
    ["EBT_CURRENCY"]            = 'EBT_CURRENCY';
    ["EBT_ENERGY"]              = 'EBT_ENERGY';
    ["EBT_PURCHASE_ADD_TIME"]   = 'EBT_PURCHASE_ADD_TIME';
    ["EBT_PURCHASE_SHOW_TURN"]  = 'EBT_PURCHASE_SHOW_TURN';
    ["EBT_PURCHASE_RESOLVE"]    = 'EBT_PURCHASE_RESOLVE';
}

